highlight:
  codeFences: true
  guessSyntax: true
  lineNos: true
  lineNumbersInTable: true
  anchorLineNos: true
  noClasses: false
  tabWidth: 2

goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true

  parser:
    attribute:
      block: true
      title: true
    autoHeadingID: true
    autoHeadingIDType: github

  renderer:
    unsafe: true

tableOfContents:
  startLevel: 2
  endLevel: 6
