baseURL: https://hakula.xyz
defaultContentLanguage: zh-cn
languageCode: zh-CN
hasCJKLanguage: true
title: HAKULA†CHANNEL
theme: LoveIt

params:
  version: 0.2.X
  description: Welcome to Hakula's personal website!
  defaultTheme: dark
  gitRepo: https://github.com/hakula139/hakula.xyz
  fingerprint: sha384

  app:
    title: Hakula
    themeColor: "#000a12"
    iconColor: "#263238"
    tileColor: "#263238"

  search:
    enable: true
    type: lunr
    contentLength: 4000
    maxResultLength: 5
    snippetLength: 50
    highlightTag: em

  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      name: Hakula.XYZ
      typeit: true

  footer:
    enable: true
    hugo: true
    copyright: true
    author: true
    since: 2018
    license: >
      <a
        href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh"
        rel="license external nofollow noopener noreferrer"
        target="_blank"
      >CC BY-NC-SA 4.0</a>

  sections:
    paginate: 10
    rss: 10

  list:
    paginate: 10
    rss: 10

  home:
    rss: 10
    profile:
      enable: true
      gravatarEmail: i@hakula.xyz
      title: HAKULA†CHANNEL
      subtitle: Hakula 的个人站！
      social: true
    posts:
      enable: true
      paginate: 10

  social:
    QQ:
      weight: 0
      id: 1517242376
      prefix: https://wpa.qq.com/msgrd?v=3&site=hakula.xyz&menu=yes&uin=
      title: QQ
      icon:
        class: fab fa-qq fa-fw
    GitHub: hakula139
    Linkedin: hakula
    Telegram: hakulaTG
    Steam: hakula139
    Zhihu: hakula139
    Bilibili: 3507112
    Email: i@hakula.xyz
    RSS: true

  page:
    twemoji: true
    lightgallery: true
    ruby: true
    fraction: true
    fontawesome: true
    toc:
      enable: true
      keepStatic: false
      auto: true
    code:
      copy: true
      maxShownLines: 24
    math:
      enable: true
      copyTex: true

  cdn:
    data: jsdelivr.yml

menu:
  main:
    - identifier: archive
      name: 文章归档
      url: /archive/
      weight: 1
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 2
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 3

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6

author:
  name: Hakula
  email: i@hakula.xyz
  link: https://hakula.xyz

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

privacy:
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

mediaTypes:
  text/plain:
    suffixes: [md]

outputFormats:
  Markdown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false

outputs:
  home: [HTML, RSS, JSON]
  page: [HTML, Markdown]
  section: [HTML, RSS]
  taxonomy: [HTML, RSS]
  taxonomyTerm: [HTML]
